<?php
/**
 * MPE2025 Theme Functions
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly
}

/**
 * Theme Setup
 */
function mpe2025_setup() {
	// Add default posts and comments RSS feed links to head.
	add_theme_support( 'automatic-feed-links' );

	// Let WordPress manage the document title.
	add_theme_support( 'title-tag' );

	// Enable support for Post Thumbnails on posts and pages.
	add_theme_support( 'post-thumbnails' );

	// add cutome img size

	add_image_size("thumb", 390, 220, true);

	// Switch default core markup for search form, comment form, and comments to output valid HTML5.
	add_theme_support( 'html5', array(
		'search-form',
		'comment-form',
		'comment-list',
		'gallery',
		'caption',
		'style',
		'script',
	) );

	// Register Navigation Menus
	register_nav_menus( array(
		'primary'      => 'Primary Menu',
		'footer_links' => 'Footer Quick Links',
	) );
}
add_action( 'after_setup_theme', 'mpe2025_setup' );

/**
 * Enqueue Scripts and Styles
 */
function mpe2025_scripts() {
	// Google Fonts - Now using local fonts for better performance
	// wp_enqueue_style( 'mpe2025-google-fonts', 'https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:ital,wght@0,200..800;1,200..800&display=swap', array(), null );
	
	// Material Icons - Removed for performance
	// wp_enqueue_style( 'mpe2025-material-icons', 'https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&display=swap', array(), null );

	// Dequeue WordPress block library styles (now integrated into our main SCSS to reduce render-blocking)
	wp_dequeue_style( 'wp-block-library' );
	wp_dequeue_style( 'wp-block-library-theme' );

	// Main Stylesheet
	$style_ver = file_exists( get_stylesheet_directory() . '/style.css' ) ? filemtime( get_stylesheet_directory() . '/style.css' ) : '1.0.0';
	wp_enqueue_style( 'mpe2025-style', get_stylesheet_uri(), array(), $style_ver );

    // Main Script
    $script_ver = file_exists( get_template_directory() . '/assets/js/main.js' ) ? filemtime( get_template_directory() . '/assets/js/main.js' ) : '1.0.0';
    wp_enqueue_script( 'mpe2025-main-script', get_template_directory_uri() . '/assets/js/main.js', array(), $script_ver, true );

	// Threaded comments
	if ( is_singular() && comments_open() && get_option( 'thread_comments' ) ) {
		wp_enqueue_script( 'comment-reply' );
	}
}
add_action( 'wp_enqueue_scripts', 'mpe2025_scripts' );

/**
 * Defer non-critical scripts
 */
function mpe2025_defer_scripts( $tag, $handle ) {
    // Do not defer scripts in admin dashboard as it breaks the editor
    if ( is_admin() ) {
        return $tag;
    }

    // List of scripts to defer
    $defer_scripts = array( 
        'wprs-unslider-swipe', 
        'wprev-public', 
        'jquery-migrate',
        'contact-form-7',
        'wp-block-library'
    );

    if ( in_array( $handle, $defer_scripts ) ) {
        return str_replace( ' src', ' defer="defer" src', $tag );
    }

    return $tag;
}
add_filter( 'script_loader_tag', 'mpe2025_defer_scripts', 10, 2 );

/**
 * Load Custom Post Types
 */
require get_template_directory() . '/inc/cpt.php';

/**
 * Load Custom Meta Boxes
 */
require get_template_directory() . '/inc/meta-boxes.php';

/**
 * Load Theme Settings
 */
require get_template_directory() . '/inc/theme-settings.php';

/**
 * Register Custom Blocks
 */
function mpe2025_register_blocks() {
	register_block_type( get_template_directory() . '/blocks/custom-post-grid' );
	register_block_type( get_template_directory() . '/blocks/trust-indicators' );
	register_block_type( get_template_directory() . '/blocks/reservation-form' );
	register_block_type( get_template_directory() . '/blocks/custom-gallery' );
}
add_action( 'init', 'mpe2025_register_blocks' );

/**
 * Pass available languages to reservation form block editor
 */
function mpe2025_enqueue_block_editor_assets() {
	// Get available languages for the block editor
	$languages = array();
	if ( function_exists( 'pll_languages_list' ) ) {
		$pll_languages = pll_languages_list( array( 'fields' => '' ) );
		foreach ( $pll_languages as $lang ) {
			$languages[] = array(
				'label' => $lang->name,
				'value' => $lang->slug,
			);
		}
	}
	
	// Fallback if Polylang is not active
	if ( empty( $languages ) ) {
		$languages = array(
			array( 'label' => 'English', 'value' => 'en' ),
			array( 'label' => 'Français', 'value' => 'fr' ),
		);
	}
	
	// The block script handle is auto-generated by WordPress as: mpe2025-reservation-form-editor-script
	// But when using file:./index.js in block.json, WordPress generates it differently
	// We need to use wp_add_inline_script on one of the core block editor scripts that loads early
	wp_add_inline_script(
		'wp-blocks',
		'window.mpeReservationFormLanguages = ' . wp_json_encode( $languages ) . ';',
		'before'
	);
}
add_action( 'enqueue_block_editor_assets', 'mpe2025_enqueue_block_editor_assets' );

/**
 * Load Form Handler
 */
require get_template_directory() . '/inc/form-handler.php';

require get_template_directory() . '/inc/google-reviews.php';

/**
 * Load Reservation Admin Functions
 */
require get_template_directory() . '/inc/admin-reservation.php';

/**
 * Load REST API Enhancements
 */
require get_template_directory() . '/inc/rest-api.php';





/**
 * Remove hide-if-js class from custom post type metaboxes in menu admin
 */
function mpe2025_fix_cpt_menu_metaboxes() {
    ?>
    <script type="text/javascript">
        jQuery(document).ready(function($) {
            // Remove hide-if-js from CPT sections in menu admin
            $('.add-post-type-service, .add-post-type-excursion, .add-post-type-vehicle').removeClass('hide-if-js');
        });
    </script>
    <?php
}
add_action( 'admin_footer-nav-menus.php', 'mpe2025_fix_cpt_menu_metaboxes' );
